http:
  port: 4027
admin:
  port: 4028
  host: localhost
apiEndpoints:
  apiDocs:
    paths:
      - /api-docs
    host: '*'
  admin:
    paths:
      - /admin
    host: '*'
serviceEndpoints:
  local:
    url: 'http://localhost:3000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines: null
