# https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters.md
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-smb
provisioner: file.csi.azure.com
mountOptions:
  # - noblocksend
  # - unix
  # - noperm
  - dir_mode=0777
  - file_mode=0777
  # - nostrictsync
  # - fsc
  # - multiuser
  - mfsymlinks
  - nobrl
  # - rwpidforward
  # - nopersistenthandles
  # - sfu
  # - uid=0
  # - gid=0
  # - cache=none
  # - persistenthandles
  # - nounix
  # - serverino
  # - mapposix
  # - rsize=1048576
  # - wsize=1048576
  # - mapchars
  # - acl
  # - actimeo=0
parameters:
  skuName: Premium_LRS
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
