apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: core-hub
  name: core-hub
  namespace: spinalcom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-hub
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: core-hub
    spec:
      containers:
      - name: spinal-core-hub
        image: docker.io/fjudith/spinal-core-hub:3.1.0-alpine
        imagePullPolicy: Always
        ports:
        - name: hub-port
          containerPort: 8888
        - name: super-port
          containerPort: 8889
        - name: soda-port
          containerPort: 8890
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/app/memory
          name: cache-volume
      - name: spinal-organ-dump-manager
        image: docker.io/fjudith/spinal-organ-dump_manager:1.0.0-alpine
        imagePullPolicy: Always
        env:
        - name: SPINALHUB_PORT
          value: "8888"
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/spinal-organ-dump_manager/memory
          name: cache-volume
      - name: spinal-organ-forge
        image: docker.io/fjudith/spinal-organ-forge:1.1.5-alpine
        imagePullPolicy: Always
        env:
        - name: SPINALHUB_PORT
          value: "8888"
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/spinal-organ-forge/memory
          name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir: {}
status: {}
