apiVersion: v1
kind: Service
metadata:
  name: http-server
  namespace: spinalcom
  labels:
    app: spinal-core
    component: http-server
spec:
  selector:
    app: spinal-core
    component: http-server
  ports:
    - name: http
      protocol: TCP
      port: 8892
      targetPort: 8892
