apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: http-server
  name: http-server
  namespace: spinalcom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: http-server
    spec:
      containers:
      - name: spinal-http-server
        image: docker.io/fjudith/spinal-caddy-server:1.0.0-alpine
        imagePullPolicy: Always
        env:
        - name: HUB_HOST
          value: core-hub
        - name: SPINALHUB_HOST
          value: core-hub
        - name: SPINALHUB_PORT
          value: "8888"
        ports:
          - name: http
            containerPort: 8892
        resources: {}
status: {}
