{
  "spinal-core-hub": {
    "env": {
      "SPINALHUB_PORT": __SPINALHUB_PORT__,
      "SPINALHUB_IP": "__SPINALHUB_HOST__",
      "SPINAL_USER_ID": "__SPINAL_USER_ID__",
      "SPINAL_PASSWORD": "__SPINAL_PASSWORD__"
    },
    "env_test": {
      "SPINALHUB_PORT": __SPINALHUB_PORT__,
      "SPINALHUB_IP": "__SPINALHUB_HOST__",
      "SPINAL_USER_ID": "__SPINAL_USER_ID__",
      "SPINAL_PASSWORD": "__SPINAL_PASSWORD__"
    },
    "env_production": {
      "SPINALHUB_PORT": __SPINALHUB_PORT__,
      "SPINALHUB_IP": "__SPINALHUB_HOST__",
      "SPINAL_USER_ID": "__SPINAL_USER_ID__",
      "SPINAL_PASSWORD": "__SPINAL_PASSWORD__"
    }
  },
  "spinal-organ-api-gateway": {
    "env": {
      "INTERVAL": __SPINAL_INTERVAL__,
      "SPINAL_USER_ID": "__SPINAL_USER_ID__",
      "SPINAL_PASSWORD": "__SPINAL_PASSWORD__",
      "SPINAL_DTWIN_PATH": "__SPINAL_DTWIN_PATH__",
      "API_GATEWAY_PORT": __SPINAL_API_GATEWAY_PORT__,
      "REQUESTS_HOST": "__SPINAL_REQUESTS_HOST__",
      "REQUESTS_PORT": __SPINAL_REQUESTS_PORT__
    },
    "env_test": {
      "INTERVAL": __SPINAL_INTERVAL__,
      "SPINAL_USER_ID": "__SPINAL_USER_ID__",
      "SPINAL_PASSWORD": "__SPINAL_PASSWORD__",
      "SPINAL_DTWIN_PATH": "__SPINAL_DTWIN_PATH__",
      "API_GATEWAY_PORT": __SPINAL_API_GATEWAY_PORT__,
      "REQUESTS_HOST": "__SPINAL_REQUESTS_HOST__",
      "REQUESTS_PORT": __SPINAL_REQUESTS_PORT__
    },
    "env_production": {
      "INTERVAL": __SPINAL_INTERVAL__,
      "SPINAL_USER_ID": "__SPINAL_USER_ID__",
      "SPINAL_PASSWORD": "__SPINAL_PASSWORD__",
      "SPINAL_DTWIN_PATH": "__SPINAL_DTWIN_PATH__",
      "API_GATEWAY_PORT": __SPINAL_API_GATEWAY_PORT__,
      "REQUESTS_HOST": "__SPINAL_REQUESTS_HOST__",
      "REQUESTS_PORT": __SPINAL_REQUESTS_PORT__
    }
  }
}